---
title: تصدیق عملکرد IPsec به طور مستقل در FreeBSD
authors:
  - author: David Honig
    email: honig@sprynet.com
releaseinfo: "$FreeBSD$" 
trademarks: ["freebsd", "opengroup", "general"]
---

= تصدیق عملکرد IPsec به طور مستقل در FreeBSD
:doctype: article
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:

IPsec را نصب کرده‌اید و به نظر می‌رسد که کار هم می‌کند. ولی از کجا می‌دانید؟ من روشی را در اینجا تشریح می‌کنم که با آن می‌توانید به طور آزمون‌گرانه تصدیق کنید که IPsec به درستی کار می‌کند.

'''

toc::[]

[[problem]]
== تعریف مشکل

ابتدا، بیایید فرض کنیم که شما <<ipsec-install,_IPsec_ را نصب کرده‌اید>>. از کجا می‌دانید که به درستی <<caveat,کار می‌کند>>؟ بله، درست است، اگر به درستی پیکربندی نشده بود اتصال شما کار نمی‌کرد، فقط وقتی آن را درست پیکربندی کرده باشید کار خواهد کرد. {man:netstat[1] آن را فهرست خواهد کرد. ولی آیا به طور مستقل هم می‌توانید آن را تصدیق کنید؟

[[solution]]
== راه حل

ابتدا، کمی اطلاعات تئوری در رابطه با رمزنگاری:

. داده‌های رمزنگاری‌شده به طور یکنواخت توزیع می‌شوند. به عبارت دیگر، به ازای هر نماد، آنتروپی بیشینه دارند؛
. داده‌های خام و فشرده‌ نشده عموما افزونگی دارند. به عبارت دیگر، آنتروپی فرو-بیشینه دارند.

فرض کنید که می‌توانستید آنتروپی داده‌های ارسالی به کارت شبکه و دریافتی از آن را اندازه‌گیری کنید. آنگاه می‌توانستید تفاوت بین داده‌های رمزنگاری‌شده و رمزنگاری‌نشده را ببینید. این گفته حتی وقتی که مقداری از داده‌ها در "حالت رمزنگاری" عملا رمزنگاری‌نشده باشند هم درست است. مثلا اگر قرار باشد بسته قابل مسیریابی باشد، آنگاه بیرونی‌ترین سرایند IP نباید رمزنگاری‌شده باشد.

[[MUST]]
=== MUST

ابزار "Universal Statistical Test for Random Bit Generators"(https://web.archive.org/web/20011115002319/http://www.geocities.com/SiliconValley/Code/4704/universal.pdf[ MUST]) یولی مائورر می‌تواند آنتروپی یک نمونه را به سرعت اندازه‌گیری کند. این ابزار از یک الگوریتم شبه-فشرده‌سازی استفاده می‌کند. کد گونه‌ای از این ابزار که قادر است به طور پیاپی (تقریبا یک چارک مگابایت) قطعات یک پرونده را اندازه‌گیری کند، <<code, در زیر آورده شده است>>.

[[tcpdump]]
=== Tcpdump

ما همچنین به روشی نیاز داریم تا بتوانیم داده‌های خام شبکه را ضبط کنیم. برنامه‌ای به نام {man:tcpdump[1] اجازه انجام چنین کاری را به ما می‌دهد. برای استفاده از آن نیاز است تا در <<kernel,پرونده پیکربندی هسته>>_Berkeley Packet Filter_ را فعال کرده باشید.

دستور:

[source,bash]
....
 tcpdump -c 4000 -s 10000 -w dumpfile.bin
....

۴۰۰۰ بسته خام را ضبط کرده و در _dumpfile.bin_ ذخیره می‌کند. در این مثال، تا ۱۰٬۰۰۰ بایت در هر بسته ضبط خواهد شد.

[[experiment]]
== آزمایش

آزمایش از این قرار است:

[.procedure]
. یک پنجره به یک میزبانِ IPsec و پنجره‌ای دیگر به یک میزبان ناامن باز کنید.
. حالا شروع به <<tcpdump,ضبط بسته‌ها>> نمایید.
. حال در پنجره "امن"، دستور یونیکسی(TM){man:yes[1] را اجرا کنید، که باعث خواهد شد کاراکتر `y` مثل یک جویبار روان شود. پس از مدتی، این دستور را متوقف کنید. به پنجره ناامن بروید و همین کار را تکرار کنید. پس از مدتی، آن را هم متوقف کنید.
. حال <<code,MUST>> را روی بسته‌های ضبط شده اجرا کنید. باید چیزی شبیه خروجی زیر را ببینید. نکته مهم این است که اتصال امن ۹۳٪ (۶.۷) از مقدار مورد انتظار (۷.۱۸) را دارد، و اتصال "عادی" تنها ۲۹٪ (۲.۱) از مقدار مورد انتظار را دارد.
+
[source,bash]
....
% tcpdump -c 4000 -s 10000 -w ipsecdemo.bin

% uliscan ipsecdemo.bin
Uliscan 21 Dec 98
L=8 256 258560
Measuring file ipsecdemo.bin
Init done
Expected value for L=8 is 7.1836656
6.9396 --------------------------------------------------------
6.6177 -----------------------------------------------------
6.4100 ---------------------------------------------------
2.1101 -----------------
2.0838 -----------------
2.0983 -----------------
....

[[caveat]]
== هشدار

این آزمایش نشان می‌دهد که IPsec ظاهرا دارد داده‌ها را _به طور یکنواخت__توزیع می‌کند_، همانطور که از یک رمزنگاری انتظار می‌رود. با این حال، آزمایشی که در اینجا شرح آن رفت _نمی‌تواند_ هیچگونه نقص احتمالی را در سامانه تشخیص دهد (که برای هیچکدام از آنها هیچ نشانه‌ای ندارم). این نقص‌ها می‌توانند چیزهایی مثل تولید کلید ضعیف یا تبادل نادرست کلیدها، در معرض نمایش بودن کلیدها یا داده‌ها برای بقیه، استفاده از الگوریتم ضعیف، تخریب هسته از درون و غیره باشند. کدمنبع را بخوانید و با آن آشنا شوید.

[[IPsec]]
== IPsec---تعریف

افزونه‌های امنیتی قرارداد اینترنت برای IPv4؛ که در IPv6 الزامی است، قراردادی است برای مذاکره کردن روش‌های رمزنگاری و احراز هویت در لایه IP (میزبان به میزبان). SSL تنها یک سوکت را ایمن می‌کند؛ SSH تنها یک ورود را ایمن می‌کند؛ PGP تنها یک پرونده یا پیغام را ایمن می‌کند. ولی IPsec همه چیز را بین دو میزبان ایمن می‌کند.

[[ipsec-install]]
== نصب IPsec

بیشتر نسخه‌های مدرن FreeBSD از IPsec در کدمنبع‌شان پشتیبانی می‌کنند. تنها نیاز است که شما گزینه `IPSEC` را در فایل پیکربندی هسته بگنجانید و پس از آنکه هسته را کامپایل و نصب کردید، با استفاده از دستور {man:setkey[8] اتصالات IPsec را پیکربندی کنید.

یک راهنمای جامع درباره راه‌اندازی IPsec در FreeBSD در link:@@URL_RELPREFIX@@/doc/en_US.ISO8859-1/books/handbook/ipsec.html[کتاب راهنمای FreeBSD] آورده شده است.
[[kernel]]
== src/sys/i386/conf/KERNELNAME

نیاز است تا آن را در فایل پیکربندی هسته گنجانده باشید تا بتوان داده‌های شبکه را با {man:tcpdump[1] ضبط کرد. مطمئن شوید که پس از اضافه کردن آن {man:config[8] را اجرا خواهید کرد، سپس هسته را مجددا کامپایل و نصب نمایید.

[.programlisting]
....
device	bpf
....

[[code]]
== Maurer's Universal Statistical Test (برای بلاک‌هایی با اندازه ۸ بیتی)

همین کد را می‌توانید در https://web.archive.org/web/20031204230654/http://www.geocities.com:80/SiliconValley/Code/4704/uliscanc.txt[ این نشانی] هم پیدا کنید.
[.programlisting]
....
/*
  ULISCAN.c   ---blocksize of 8

  1 Oct 98
  1 Dec 98
  21 Dec 98       uliscan.c derived from ueli8.c

  This version has // comments removed for Sun cc

  This implements Ueli M Maurer's "Universal Statistical Test for Random
  Bit Generators" using L=8

  Accepts a filename on the command line; writes its results, with other
  info, to stdout.

  Handles input file exhaustion gracefully.

  Ref: J. Cryptology v 5 no 2, 1992 pp 89-105
  also on the web somewhere, which is where I found it.

  -David Honig
  honig@sprynet.com

  Usage:
  ULISCAN filename
  outputs to stdout
*/

#define L 8
#define V (1<<L)
#define Q (10*V)
#define K (100   *Q)
#define MAXSAMP (Q + K)

#include <stdio.h>
#include <math.h>

int main(argc, argv)
int argc;
char **argv;
{
  FILE *fptr;
  int i,j;
  int b, c;
  int table[V];
  double sum = 0.0;
  int iproduct = 1;
  int run;

  extern double   log(/* double x */);

  printf("Uliscan 21 Dec 98 \nL=%d %d %d \n", L, V, MAXSAMP);

  if (argc < 2) {
    printf("Usage: Uliscan filename\n");
    exit(-1);
  } else {
    printf("Measuring file %s\n", argv[1]);
  }

  fptr = fopen(argv[1],"rb");

  if (fptr == NULL) {
    printf("Can't find %s\n", argv[1]);
    exit(-1);
  }

  for (i = 0; i < V; i++) {
    table[i] = 0;
  }

  for (i = 0; i < Q; i++) {
    b = fgetc(fptr);
    table[b] = i;
  }

  printf("Init done\n");

  printf("Expected value for L=8 is 7.1836656\n");

  run = 1;

  while (run) {
    sum = 0.0;
    iproduct = 1;

    if (run)
      for (i = Q; run && i < Q + K; i++) {
        j = i;
        b = fgetc(fptr);

        if (b < 0)
          run = 0;

        if (run) {
          if (table[b] > j)
            j += K;

          sum += log((double)(j-table[b]));

          table[b] = i;
        }
      }

    if (!run)
      printf("Premature end of file; read %d blocks.\n", i - Q);

    sum = (sum/((double)(i - Q))) /  log(2.0);
    printf("%4.4f ", sum);

    for (i = 0; i < (int)(sum*8.0 + 0.50); i++)
      printf("-");

    printf("\n");

    /* refill initial table */
    if (0) {
      for (i = 0; i < Q; i++) {
        b = fgetc(fptr);
        if (b < 0) {
          run = 0;
        } else {
          table[b] = i;
        }
      }
    }
  }
}
....
