---
title: Guía para el manejo de informes de problemas
authors:
  - author: Dag-Erling Smørgrav
  - author: Hiten Pandya
releaseinfo: "$FreeBSD$" 
trademarks: ["freebsd", "general"]
---

= Guía para el manejo de informes de problemas
:doctype: article
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:lang: es
:toc-title: Tabla de contenidos
:part-signifier: Parte
:chapter-signifier: Capítulo
:appendix-caption: Apéndice
:table-caption: Tabla
:figure-caption: Figura
:example-caption: Ejemplo

include::shared/es/urls.adoc[]

[.abstract-title]
Resumen

Esta guía describe las prácticas recomendadas para manejar los informes de problemas (PRs) de FreeBSD. Aunque se desarrolló para el FreeBSD PR database maintenance team mailto:freebsd-bugbusters@FreeBSD.org[freebsd-bugbusters@FreeBSD.org], cualquiera que trabaje con PRs de FreeBSD debe seguir estas pautas.

'''

toc::[]

[[intro]]
== Introducción

Bugzilla es un sistema de gestión de errores utilizado por el proyecto FreeBSD. Un seguimiento preciso de los defectos de software pendientes es importante para la calidad de FreeBSD, el uso correcto del software es esencial para el progreso del proyecto.

El acceso a Bugzilla está disponible para toda la comunidad de FreeBSD. Con el fin de mantener la coherencia dentro de la base de datos y proporcionar una experiencia de usuario consistente, se han establecido pautas que cubren aspectos comunes de la gestión de errores, como la presentación del seguimiento, el manejo de las solicitudes de cierre, etc.

[[pr-lifecycle]]
== Ciclo de vida de un informe de problemas

* El usuario envía un informe de error al sitio web. El error está en el estado `Needs Triage`.
* Jane Random BugBuster confirma que el error reportado tiene la suficiente información para ser reproducido. Si no, se interactuará repetidamente con el usuario para obtener la información necesaria. En este punto, el error se establece en el estado `Open`.
* Joe Random Committer se interesa por el PR y se lo asigna a si mismo, o Jane Random BugBuster decide que Joe es la persona más adecuada para resolver el problema y le asigna error. El error se debe poner en el estado `In Discussion`.
* Joe tiene una breve conversación con el usuario que ha enviado el informe del problema (asegurándose de que todo queda registrado) y determina la causa.
* Joe está toda la noche trabajando y elabora un parche que cree que soluciona el problema, y lo envía en un follow-up, pidiéndole al usuario que lo ha enviado que lo pruebe. A continuación, fija el estado del PR en `Patch Ready`.
* Un par de iteraciones más tarde, tanto Joe como el usuario que lo ha creado están satisfechos con el parche, y Joe realiza el commit a `-CURRENT` (o directamente a `-STABLE` si el problema no existe en `-CURRENT`), asegurándose de hacer referencia al informe de problemas en su log del commit (y dando el crédito al usuario si envió todo o parte del parche) y, si corresponde, iniciará una cuenta atrás de MFC. El error se fija en el estado `Needs MFC`.
* Si el parche no necesita pasar por un MFC, Joe entonces cierra el PR con el estado `Issue Resolved`.

[NOTE]
====
Muchos PRs son enviados con muy poca información sobre el problema, y algunos son muy complejos de resolver, o simplemente arañan la superficie de un problema mayor; en estos casos, es muy importante obtener toda la información necesaria para resolver el problema. Si el problema no se puede resolver, o si ha ocurrido nuevamente, es necesario volver a abrir el PR.
====

[[pr-states]]
== Estados de los informes de problemas

Es importante actualizar el estado de un PR cuando se toman ciertas acciones. El estado debe reflejar con precisión la situación actual del trabajo en el PR.

.Un pequeño ejemplo de cuándo cambiar el estado de un PR
[example]
====
Cuando un PR haya sido tratado y el desarrollador/es se sienta cómodo con la solución, enviará un follow-up al PR y cambiará su estado a "feedback". En este punto, el usuario que lo ha creado debe evaluar la solución en su contexto y responder indicando si el defecto ha sido solucionado.
====

Un informe de problemas puede estar en uno de los siguientes estados:

[.glosslist]
Abrir::
Estado inicial; el problema ha sido indicado y necesita ser revisado.

analizar::
El problema ha sido revisado y se está buscando una solución.

retroalimentación::
Si hay que realizar trabajo adicional, esto requiere información adicional del usuario o de la comunidad; posiblemente información sobre la solución propuesta.

patched::
Se ha realizado un commit con el parche, pero aún hay algo pendiente (MFC, o tal vez confirmación del usuario que lo creó).

suspendido::
No se está trabajando en el problema debido a la falta de información o recursos. Este es un candidato excelente para alguien que está buscando un proyecto. Si el problema no se puede resolver, se cerrará, en lugar de suspenderse. El proyecto de documentación utiliza suspended para los elementos de la wish-list que implican una cantidad significativa de trabajo para el cual nadie tiene tiempo actualmente.

cerrado::
Un informe de problemas se cierra cuando se han integrado, documentado y probado los cambios, o cuando se abandona la solución del problema.

[NOTE]
====
El estado "patched" está directamente relacionado con el feedback, por lo que puede ir directamente al estado "closed" si el usuario que lo creó no puede probar el parche y funciona en sus propias pruebas.
====

[[pr-types]]
== Tipos de informes de problemas

Al tratar con informes de problemas, ya sea como desarrollador que tiene acceso directo a la base de datos de informes de problemas o como colaborador que navega por la base de datos y envía follow-ups con parches, comentarios, sugerencias o solicitudes de cambio, encontrará varios tipos diferentes de PRs.

* <<pr-unassigned,PRs que todavía no están asignados a nadie>>
* <<pr-assigned,PRs asignados a alguien>>
* <<pr-dups,Duplicados de PRs existentes>>
* <<pr-stale,PRs obsoletos>>
* <<pr-misfiled-notpr,PRs que no están relacionados con errores>>

Las siguientes secciones describen para qué se usa cada tipo de PRs, cuándo un PR pertenece a uno de estos tipos y qué tratamiento recibe cada tipo.

[[pr-unassigned]]
== PRs sin asignar

Cuando los PRs llegan, inicialmente se asignan a un responsable genérico (placeholder). Estos siempre tienen el prefijo `freebsd-`. El valor exacto para este patrón depende de la categoría; en la mayoría de los casos, corresponde a una lista de correo específica de FreeBSD. Aquí está la lista actual, con las más comunes primero:

[[default-assignees-common]]
.Asignaciones predeterminadas -- más comunes
[cols="1,1,1", options="header"]
|===
| Tipo
| Categorías
| Asignación predeterminada

|sistema base
|bin, conf, gnu, kern, misc
|freebsd-bugs

|arquitectura específica
|alpha, amd64, arm, i386, ia64, powerpc, sparc64
|freebsd-_arch_

|colección de ports
|ports
|freebsd-ports-bugs

|documentación enviada junto con el sistema
|docs
|freebsd-doc

|páginas web de FreeBSD (sin incluir docs)
|sitio web
|freebsd-www
|===

[[default-assignees-other]]
.Asignaciones predeterminadas -- otros
[cols="1,1,1", options="header"]
|===
| Tipo
| Categorías
| Asignación predeterminada

|labores de promoción
|promoción
|freebsd-advocacy

|problemas con la Java Virtual Machine(TM)
|java
|freebsd-java

|cumplimiento de estándares
|estándares
|freebsd-standards

|bibliotecas de threading
|threads
|freebsd-threads

|subsistema man:usb[4]
|usb
|freebsd-usb
|===

No se sorprenda al descubrir que el usuario responsable del PR lo ha asignado a la categoría incorrecta. Si usted arregla la categoría, no se olvide de corregir también la asignación. (En particular, nuestros usuarios parecen tener dificultades para entender que aunque su problema ocurra en un sistema i386, podría ser genérico de todo FreeBSD y, por lo tanto, ser más adecuado para `kern`. Lo contrario también es cierto, por supuesto.)

Algunos PRs pueden ser reasignados lejos de estos responsables genéricos por cualquier persona. Hay varios tipos de responsables: listas de correo especializadas; alias de correo (utilizados para ciertos artículos de interés limitado); y los individuos.

Para los responsables que son listas de correo, utilice la designación larga al realizar la asignación (por ejemplo, `freebsd-foo` en lugar de `foo`); esto evitará los mensajes de correo electrónico duplicados enviados a la lista de correo.

[NOTE]
====
Como la lista de personas que se han ofrecido voluntarias para ser los responsables predeterminados para ciertos tipos de PRs cambia con bastante frecuencia, es mucho más adecuada la https://wiki.freebsd.org/AssigningPRs[wiki de FreeBSD].
====

Aquí hay un listado de ejemplo de dichas entidades; probablemente no esté completo.

[[common-assignees-base]]
.Responsables comunes -- sistema base
[cols="1,1,1,1", options="header"]
|===
| Tipo
| Categoría sugerida
| Responsable sugerido
| Tipo de responsable

|problema específico de la arquitectura ARM(TM).
|arm
|freebsd-arm
|lista de correo

|problema específico de la arquitectura MIPS(TM)
|kern
|freebsd-mips
|lista de correo

|problema específico de la arquitectura PowerPC(TM)
|kern
|freebsd-ppc
|lista de correo

|problema con la interfaz avanzada de configuración y energía (man:acpi[4])
|kern
|freebsd-acpi
|lista de correo

|problema con los controladores del modo de transferencia asíncrono (ATM)
|kern
|freebsd-atm
|lista de correo

|problemas con sistemas FreeBSD embebidos o de small-footprint (por ejemplo, NanoBSD/PicoBSD/FreeBSD-arm)
|kern
|freebsd-embedded
|lista de correo

|problema con los controladores de FireWire(TM)
|kern
|freebsd-firewire
|lista de correo

|problema con el código fuente del sistema de archivos
|kern
|freebsd-fs
|lista de correo

|problema con el subsistema man:geom[4]
|kern
|freebsd-geom
|lista de correo

|problema con el subsistema man:ipfw[4]
|kern
|freebsd-ipfw
|lista de correo

|problema con los controladores de la red digital de servicios integrados (ISDN)
|kern
|freebsd-isdn
|lista de correo

|subsistema man:jail[8]
|kern
|freebsd-jail
|lista de correo

|problema con la emulación Linux(TM) o SVR4
|kern
|freebsd-emulation
|lista de correo

|problema con el stack de red
|kern
|freebsd-net
|lista de correo

|problema con el subsistema man:pf[4]
|kern
|freebsd-pf
|lista de correo

|problema con el subsistema man:scsi[4]
|kern
|freebsd-scsi
|lista de correo

|problema con el subsistema man:sound[4]
|kern
|freebsd-multimedia
|lista de correo

|problema con el subsistema y controladores wireless man:wlan[4]
|kern
|freebsd-wireless
|lista de correo

|problema con man:sysinstall[8] o man:bsdinstall[8]
|bin
|freebsd-sysinstall
|lista de correo

|problema con los scripts de inicio del sistema (man:rc[8])
|kern
|freebsd-rc
|lista de correo

|problema con la funcionalidad VIMAGE o VNET y el código relacionado
|kern
|freebsd-virtualization
|lista de correo

|problema con la emulación de Xen
|kern
|freebsd-xen
|lista de correo
|===

[[common-assignees-ports]]
.Responsables comunes -- coleción de ports
[cols="1,1,1,1", options="header"]
|===
| Tipo
| Categoría sugerida
| Responsable sugerido
| Tipo de responsable

|problema con el framework de ports (¡_no_ con un port en concreto!)
|ports
|portmgr
|alias

|port que es mantenido por apache@FreeBSD.org
|ports
|apache
|lista de correo

|port que es mantenido por autotools@FreeBSD.org
|ports
|autotools
|alias

|port que es mantenido por doceng@FreeBSD.org
|ports
|doceng
|alias

|port que es mantenido por eclipse@FreeBSD.org
|ports
|freebsd-eclipse
|lista de correo

|port que es mantenido por gecko@FreeBSD.org
|ports
|gecko
|lista de correo

|port que es mantenido por gnome@FreeBSD.org
|ports
|gnome
|lista de correo

|port que es mantenido por hamradio@FreeBSD.org
|ports
|hamradio
|alias

|port que es mantenido por haskell@FreeBSD.org
|ports
|haskell
|alias

|port que es mantenido por java@FreeBSD.org
|ports
|freebsd-java
|lista de correo

|port que es mantenido por kde@FreeBSD.org
|ports
|kde
|lista de correo

|port que es mantenido por mono@FreeBSD.org
|ports
|mono
|lista de correo

|port que es mantenido por office@FreeBSD.org
|ports
|freebsd-office
|lista de correo

|port que es mantenido por perl@FreeBSD.org
|ports
|perl
|lista de correo

|port que es mantenido por python@FreeBSD.org
|ports
|freebsd-python
|lista de correo

|port que es mantenido por ruby@FreeBSD.org
|ports
|freebsd-ruby
|lista de correo

|port que es mantenido por secteam@FreeBSD.org
|ports
|secteam
|alias

|port que es mantenido por vbox@FreeBSD.org
|ports
|vbox
|alias

|port que es mantenido por x11@FreeBSD.org
|ports
|freebsd-x11
|lista de correo
|===

Los PRs relacionados con los ports que tienen un maintainer que es a la vez un committer de ports pueden ser reasignados por cualquiera (pero tenga en cuenta que no todo committer de FreeBSD es necesariamente un committer de ports, por lo que no puede guiarse únicamente por la dirección de correo electrónico).

Para otros PRs, por favor, no los reasigne a otros individuos (otros que no sean usted), a menos que esté seguro de que el responsable realmente quiere mantenerse al tanto del PR. Esto ayudará a evitar situaciones en las que nadie se dedica a solucionar un problema en particular porque todos asumen que el responsable ya está trabajando en ello.

[[common-assignees-other]]
.Responsables comunes -- otros
[cols="1,1,1,1", options="header"]
|===
| Tipo
| Categoría sugerida
| Responsable sugerido
| Tipo de responsable

|problema con la base de datos de PR
|bin
|bugmeister
|alias

|problema con el https://bugs.freebsd.org/submit/[formulario web] de Bugzilla.
|doc
|bugmeister
|alias
|===

[[pr-assigned]]
== PRs asignados

Si un PR tiene el campo `responsible` establecido con el nombre de usuario de un desarrollador de FreeBSD, significa que el PR se ha entregado a esa persona en particular para un trabajo adicional.

Los PRs asignados no deben ser tocados por nadie más que el responsable o el bugmeister. Si tiene comentarios, envíe un follow-up. Sí, por algún motivo, cree que el PR debe cambiar de estado o ser reasignado, envíe un mensaje al responsable. Si el responsable no responde en dos semanas, anule la asignación del PR y haga lo que quiera.

[[pr-dups]]
== PRs duplicados

Si encuentra más de un PR que describe el mismo problema, elija el que contiene la mayor cantidad de información útil y cierre los demás, indicando claramente el número de PR sustituidos. Si varios PRs contienen información útil que no está repetida, envíe toda la información restante en un follow-up, incluidas las referencias a los demás; luego cierre los otros PRs (que ya han sido completamente reemplazados).

[[pr-stale]]
== PRs obsoletos

Un PR se considera obsoleto si no ha sido modificado en más de seis meses. Realice el siguiente procedimiento para tratar los PRs obsoletos:

* Si el PR contiene suficientes detalles, intente reproducir el problema en `-CURRENT` y en `-STABLE`. Si tiene éxito, envíe un follow-up detallando sus descubrimientos e intente encontrar a alguien a quien asignárselo. Establezca el estado en "analyzed" si corresponde.
* Si el PR describe un problema que sabe que es el resultado de un error de uso (configuración incorrecta o de otro tipo), envíe un follow-up que explique qué hizo mal el usuario, luego cierre el PR con el motivo "User error" o "Configuration error".
* Si el PR describe un error que sabe que ha sido corregido tanto en `-CURRENT` como en `-STABLE`, ciérrelo con un mensaje que indique cuándo se solucionó en cada rama.
* Si el PR describe un error que sabe que ha sido corregido en `-CURRENT`, pero no en `-STABLE`, intente averiguar cuándo la persona que lo corrigió está planeando el MFC, o intente encontrar a alguien más (¿quizás usted mismo?) para hacerlo. Establezca el estado en "patched" y asígnelo a quien quiera que se haya encargado de hacer el MFC.
* En otros casos, solicite al usuario que confirme si el problema persiste en las versiones más nuevas. Si el usuario no responde en un mes, cierre el PR con la anotación "Feedback timeout".

[[pr-misfiled-notpr]]
== PRs sin errores

Los desarrolladores que se encuentren con PRs que parecen haber sido publicados en http://lists.FreeBSD.org/mailman/listinfo/freebsd-bugs[freebsd-bugs] o alguna otra lista, deberían cerrar el PR, informando al usuario en un comentario indicando por qué el problema reportado no es realmente un PR y dónde debe publicarse el mensaje.

Las direcciones de correo electrónico que utiliza Bugzilla para recibir los PR se han publicado como parte de la documentación de FreeBSD, se han anunciado y se enumeran en el sitio web. Esto significa que los spammers las encontraron.

Cuando cierre uno de estos PRs, haga lo siguiente:

* Establezca el componente en `junk` (en `Supporting Services`).
* Establezca como responsable a `nobody@FreeBSD.org`.
* Establezca el estado en `Issue Resolved`.

Establecer la categoría en `junk` indica que no hay contenido útil dentro del PR y ayuda a reducir el desorden en las categorías principales.

[[references]]
== Otras lecturas

Esta es una lista de recursos relevantes para la correcta escritura y procesamiento de informes de problemas. De ninguna manera debe considerarse completa.

* link:{problem-reports}[Cómo escribir informes de problemas para FreeBSD] -- directrices para los usuarios que envían un PR.
