---
title: Uavhengig verifisering av IPsec-funksjonalitet i FreeBSD
authors: 
  - author: David Honig
    email: honig@sprynet.com
releaseinfo: "$FreeBSD$" 
trademarks: [] 
---

= Uavhengig verifisering av IPsec-funksjonalitet i FreeBSD
:doctype: article
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:

[.abstract-title]
Abstract

Du har installert IPsec og det ser ut til å fungere. Hvordan vet du at det fungerer som det skal? Jeg skal beskrive en eksperimentell metode som bekrefter at IPsec fungerer.

'''

toc::[]

[[problem]]
== Problemet

Først, la oss anta at du har <<ipsec-install, installert _IPsec_>>. Hvordan vet du at det <<caveat,fungerer>>? Jada, forbindelsen din vil ikke fungere hvis den er feilkonfigurert, og den vil fungere når du endelig får det riktig. man::netstat[1] vill liste det. Men kan du uavhengig bekrefte det? 

[[solution]]
== Løsningen

Først, noe krypto-relevant teori:

. Krypterte data er ensartet distribuert, dvs. har maksimal entropi per symbol;
. Rå, ukomprimerte data er typisk overflødige, dvs. har sub-maksimal entropi.

Anta at du kan måle entropien til dataene til og fra nettverksgrensesnittet ditt. Da kunne du se forskjellen mellom ikke-krypterte data og krypterte data. Dette vil være sant, selv om noen av dataene i " kryptert modus " ikke var kryptert --- som den ytterste IP-overskriften må være hvis pakken skal være rutbar.

[[MUST]]
=== MÅ

Ueli Maurers " Universal Statistical Test for Random Bit Generators "(https://web.archive.org/web/20011115002319/http://www.geocities.com/SiliconValley/Code/4704/universal.pdf[ MUST]) måler raskt entropien til en prøve. Den bruker en kompresjonslignende algoritme. <<code, Koden er gitt nedenfor >> for en variant som måler suksessive (~ kvart megabyte) biter av en fil.

[[tcpdump]]
=== Tcpdump

We trenger også en metode for å fange rådata fra nettverket. Et program med navn man::tcpdump[1]lar deg gjøre dette, hvis du har aktivert _Berkeley Packet Filter_ brukergrensesnittet i din <<kernel,kernel's konfigurasjons fil>>.

Kommandoen:

[source,bash]
....
 tcpdump -c 4000 -s 10000 -w dumpfile.bin
....

Vil fange 4000 rå pakker til _dumpfile.bin_. Opp til 10,000 bytes pr pakke vil bli fanget i dette eksempelet.

[[experiment]]
== Eksperimentet

Her er eksperimentet:

[.procedure]
. Åpne et vindu til en IPsec vert og et annet vindu til en usikker vert.
. Start så <<tcpdump,fange pakker>>.
. I det "sikre" vinduet, kjør UNIX(TM) command man::yes[1], som vil streame `y` tegnet. Stopp dette etter en stund. Bytt til det usikre vinduet, og gjenta. Etter en stund, stopp.
. Kjør nå <<code,MUST>> på de fangede pakker. Du bør se noe som det følgende. Det viktige å merke seg er at den sikre tilkoblingen har 93% (6,7) av den forventede verdien (7.18), og "normal" tilkoblingen har 29% (2.1) av den forventede verdien.
+
[source,bash]
....
% tcpdump -c 4000 -s 10000 -w ipsecdemo.bin

% uliscan ipsecdemo.bin
Uliscan 21 Dec 98
L=8 256 258560
Measuring file ipsecdemo.bin
Init done
Expected value for L=8 is 7.1836656
6.9396 --------------------------------------------------------
6.6177 -----------------------------------------------------
6.4100 ---------------------------------------------------
2.1101 -----------------
2.0838 -----------------
2.0983 -----------------
....

[[caveat]]
== Forbeholdet

Dette eksperimentet viser at IPsec _does_ ser ut til å distribuere nyttelastdataene _uniformert_, som kryptering burde. Imidlertid _kan ikke_ eksperimentet som er beskrevet her, oppdage mange mulige feil i et system (hvorav ingen har jeg bevis for). Disse inkluderer dårlig nøkkelgenerering eller utveksling, data eller nøkler er synlige for andre, bruk av svake algoritmer, kjerneundersøkelse, etc. Studer kilden; kjenner koden.

[[IPsec]]
== IPsec---Definisjon

Internet Protocol sikkerhetsutvidelser til IPv4; påkrevd for IPv6. En protokoll for forhandling av kryptering og autentisering på IP-nivå (vert-til-vert) -nivå. SSL sikrer bare én applikasjonsuttak; SSH sikrer bare innlogging; PGP sikrer bare en spesifisert fil eller melding. IPsec krypterer alt mellom to verter.

[[ipsec-install]]
== Installere IPsec

De fleste av de moderne versjonene av FreeBSD har IPsec-støtte i basekilden. Så du må inkludere alternativet `IPSEC` i kjernekonfigurasjonen din, og etter at kernen er gjenoppbygd og installert på nytt, konfigurerer du IPsec-tilkoblinger ved å bruke man::setkey[8] kommandoen.

En omfattende guide for å kjøre IPsec på FreeBSD finnes i link:{handbook}#ipsec[FreeBSD Handbook].

[[kernel]]
== src/sys/i386/conf/KERNELNAME

Dette må være til stede i kjernekonfigurasjonsfilen for å fange nettverksdata med man::tcpdump[1]. Sørg for å kjøre man::config[8] etter å ha lagt til dette, og gjenoppbygg og installer på nytt.

[.programlisting]
....
device	bpf
....

[[code]]
== Maurer's Universal Statistical Test (for block size=8 bits)

Du kan finne den samme koden her https://web.archive.org/web/20031204230654/http://www.geocities.com:80/SiliconValley/Code/4704/uliscanc.txt[this link].

[.programlisting]
....
/*
  ULISCAN.c   ---blocksize of 8

  1 Oct 98
  1 Dec 98
  21 Dec 98       uliscan.c derived from ueli8.c

  This version has // comments removed for Sun cc

  This implements Ueli M Maurer's "Universal Statistical Test for Random
  Bit Generators" using L=8

  Accepts a filename on the command line; writes its results, with other
  info, to stdout.

  Handles input file exhaustion gracefully.

  Ref: J. Cryptology v 5 no 2, 1992 pp 89-105
  also on the web somewhere, which is where I found it.

  -David Honig
  honig@sprynet.com

  Usage:
  ULISCAN filename
  outputs to stdout
*/

#define L 8
#define V (1<<L)
#define Q (10*V)
#define K (100   *Q)
#define MAXSAMP (Q + K)

#include <stdio.h>
#include <math.h>

int main(argc, argv)
int argc;
char **argv;
{
  FILE *fptr;
  int i,j;
  int b, c;
  int table[V];
  double sum = 0.0;
  int iproduct = 1;
  int run;

  extern double   log(/* double x */);

  printf("Uliscan 21 Dec 98 \nL=%d %d %d \n", L, V, MAXSAMP);

  if (argc < 2) {
    printf("Usage: Uliscan filename\n");
    exit(-1);
  } else {
    printf("Measuring file %s\n", argv[1]);
  }

  fptr = fopen(argv[1],"rb");

  if (fptr == NULL) {
    printf("Can't find %s\n", argv[1]);
    exit(-1);
  }

  for (i = 0; i < V; i++) {
    table[i] = 0;
  }

  for (i = 0; i < Q; i++) {
    b = fgetc(fptr);
    table[b] = i;
  }

  printf("Init done\n");

  printf("Expected value for L=8 is 7.1836656\n");

  run = 1;

  while (run) {
    sum = 0.0;
    iproduct = 1;

    if (run)
      for (i = Q; run && i < Q + K; i++) {
        j = i;
        b = fgetc(fptr);

        if (b < 0)
          run = 0;

        if (run) {
          if (table[b] > j)
            j += K;

          sum += log((double)(j-table[b]));

          table[b] = i;
        }
      }

    if (!run)
      printf("Premature end of file; read %d blocks.\n", i - Q);

    sum = (sum/((double)(i - Q))) /  log(2.0);
    printf("%4.4f ", sum);

    for (i = 0; i < (int)(sum*8.0 + 0.50); i++)
      printf("-");

    printf("\n");

    /* refill initial table */
    if (0) {
      for (i = 0; i < Q; i++) {
        b = fgetc(fptr);
        if (b < 0) {
          run = 0;
        } else {
          table[b] = i;
        }
      }
    }
  }
}
....
